// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDdMC7Lu1mEIfmQyQr26-IJ9yb_eHf2Q',
    appId: '1:269337982127:web:b8ca2dbfe5a3d4459ad05a',
    messagingSenderId: '269337982127',
    projectId: 'booking-app-c3eb2',
    authDomain: 'booking-app-c3eb2.firebaseapp.com',
    storageBucket: 'booking-app-c3eb2.firebasestorage.app',
    measurementId: 'G-XVY2C8CL07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgZahmzUaLDa0PDL7gbDS7xIqjQKI7Mko',
    appId: '1:269337982127:android:553f76ab8ba664389ad05a',
    messagingSenderId: '269337982127',
    projectId: 'booking-app-c3eb2',
    storageBucket: 'booking-app-c3eb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFmb2npsL4XIVi7Ey8gt3v-avh4oVhxP4',
    appId: '1:269337982127:ios:b69cf9c3faf14f6f9ad05a',
    messagingSenderId: '269337982127',
    projectId: 'booking-app-c3eb2',
    storageBucket: 'booking-app-c3eb2.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );
}
